language: python
branches:
  only:
  - master
install:
- pip install pelican
- pip install markdown
- pip install typogrify
- pip install ghp-import
- pip install lxml requests slugify python-slugify
script:
- sh builder.sh
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
  - secure: IOkp06DKurrAYXNhOLKe2mEw4UjbAnPUDhYRmMlvQUstiKDHqtirfxw67AEGYr2/btbOTEZfBbZ+nIJg4kIODMEVdyfUxS2jcadHmbkkOjUbMh8cVmh3Xw2J53Vkh4CW//qhboayX7qIob1MSgLUqda+oRghOTnJsg9iyIC0Wno=
